# Generated by Django 5.1.2 on 2025-01-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
