# Generated by Django 5.1.2 on 2025-01-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0005_project_created_at_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_effort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='effort_estimation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='gantt_app.project')),
            ],
        ),
    ]
