# Generated by Django 5.1.2 on 2025-01-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0006_task_actual_effort_task_effort_estimation_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_upload_file', 'Can upload file'), ('can_create_folder', 'Can create folder'), ('can_delete_file', 'Can delete file'), ('can_rename_file', 'Can rename file')]},
        ),
    ]
