# Generated by Django 5.1.2 on 2025-01-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_upload_file', 'Can upload file'), ('can_create_folder', 'Can create folder'), ('can_delete_file', 'Can delete file'), ('can_rename_file', 'Can rename file')]},
        ),
    ]
