# Generated by Django 5.1.2 on 2025-01-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0008_alter_project_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user_can_upload_file', 'Can upload file'), ('user_can_create_folder', 'Can create folder'), ('user_can_delete_file', 'Can delete file'), ('user_can_rename_file', 'Can rename file')]},
        ),
    ]
