# Generated by Django 5.1.2 on 2025-01-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0010_alter_project_assigned_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gantt_app.team'),
        ),
    ]
