# Generated by Django 5.1.2 on 2025-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0014_alter_project_assigned_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
    ]
