# Generated by Django 5.1.2 on 2025-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt_app', '0015_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('cancel_deletion_request', 'Cancel Deletion Request'), ('create_project', 'Create Project'), ('create_user', 'Create User'), ('delete_project', 'Delete Project'), ('delete_user', 'Delete User'), ('edit_project', 'Edit Project'), ('edit_user', 'Edit User'), ('failed_login', 'Failed Login'), ('login', 'User Logged In'), ('message_deleted', 'Message Deleted'), ('message_edited', 'Message Edited'), ('message_sent', 'Message Sent'), ('task_created', 'Task Created'), ('task_deleted', 'Task Deleted'), ('task_edited', 'Task Edited'), ('task_status_updated', 'Task Status Updated'), ('team_created', 'Team Created'), ('team_deleted', 'Team Deleted'), ('team_leader_changed', 'Team Leader Changed'), ('team_member_added', 'Team Member Added'), ('team_member_removed', 'Team Member Removed'), ('team_updated', 'Team Updated'), ('update_profile', 'Update Profile')], max_length=50),
        ),
    ]
