# Generated by Django 5.1.2 on 2025-01-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstep',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='taskstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
