# Generated by Django 5.1.2 on 2025-01-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpms_app', '0002_remove_taskstep_is_completed_taskstep_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskissue',
            name='task',
        ),
        migrations.AddField(
            model_name='taskissue',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cpms_app.taskstep'),
            preserve_default=False,
        ),
    ]
