# Generated by Django 5.1.2 on 2025-01-25 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpms_app', '0003_remove_taskissue_task_taskissue_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ManyToManyField(related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
