# Generated by Django 5.1.2 on 2025-01-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpms_app', '0007_alter_task_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskissue',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
