# Generated by Django 5.1.2 on 2025-01-31 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpms_app', '0008_taskissue_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskissue',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
